package com.korit.clovapi.domain.plan.controller;
import com.korit.clovapi.domain.plan.dto.*; import com.korit.clovapi.domain.plan.service.PlanService; import com.korit.clovapi.global.response.ApiResponse; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.*;
@RestController @RequestMapping("/api/v1") public class PlanController {private final PlanService s;public PlanController(PlanService s){this.s=s;}private long u(Authentication a){return (Long)a.getPrincipal();}
@PostMapping("/rooms/{roomId}/plans") public ResponseEntity<ApiResponse<PlanResponses.Detail>> create(Authentication a,@PathVariable long roomId,@Valid @RequestBody PlanRequests.Create r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(s.create(roomId,u(a),r)));}
@GetMapping("/rooms/{roomId}/plans") public ApiResponse<PlanResponses.Items<PlanResponses.Summary>> list(Authentication a,@PathVariable long roomId,@RequestParam(required=false) String status,@RequestParam(required=false) LocalDate from,@RequestParam(required=false) LocalDate to){return ApiResponse.success(s.list(roomId,u(a),status,from,to));}
@GetMapping("/plans/{planId}") public ApiResponse<PlanResponses.Detail> detail(Authentication a,@PathVariable long planId){return ApiResponse.success(s.detail(planId,u(a)));}
@PatchMapping("/plans/{planId}") public ApiResponse<PlanResponses.Detail> update(Authentication a,@PathVariable long planId,@Valid @RequestBody PlanRequests.Update r){return ApiResponse.success(s.update(planId,u(a),r));}
@DeleteMapping("/plans/{planId}") public ApiResponse<Void> delete(Authentication a,@PathVariable long planId){s.delete(planId,u(a));return ApiResponse.success(null);}
@PostMapping("/plans/{planId}/complete") public ApiResponse<PlanResponses.Detail> complete(Authentication a,@PathVariable long planId){return ApiResponse.success(s.complete(planId,u(a)));}
@PostMapping("/plans/{planId}/cancel") public ApiResponse<PlanResponses.Detail> cancel(Authentication a,@PathVariable long planId){return ApiResponse.success(s.cancel(planId,u(a)));}
@PostMapping("/plans/{planId}/skip-memory") public ApiResponse<PlanResponses.Detail> skip(Authentication a,@PathVariable long planId){return ApiResponse.success(s.skip(planId,u(a)));}
@GetMapping("/plans/{planId}/stage-photos") public ApiResponse<PlanResponses.Items<PlanResponses.Stage>> stages(Authentication a,@PathVariable long planId){return ApiResponse.success(s.stages(planId,u(a)));}
@PostMapping("/plans/{planId}/stage-photos/presign") public ApiResponse<PlanResponses.Presign> presign(Authentication a,@PathVariable long planId,@Valid @RequestBody PlanRequests.Presign r){return ApiResponse.success(s.presign(planId,u(a),r));}
@PostMapping("/plans/{planId}/stage-photos") public ApiResponse<PlanResponses.Stage> commit(Authentication a,@PathVariable long planId,@Valid @RequestBody PlanRequests.Stage r){return ApiResponse.success(s.commit(planId,u(a),r));}}
