package com.korit.clovapi.domain.plan.service;
import com.korit.clovapi.domain.plan.dto.*; import com.korit.clovapi.domain.plan.entity.*; import com.korit.clovapi.domain.plan.mapper.*; import com.korit.clovapi.domain.room.mapper.RoomMemberMapper; import com.korit.clovapi.global.exception.*; import org.springframework.stereotype.*; import org.springframework.transaction.annotation.*; import java.time.*; import java.util.*;
@Service public class PlanService { private static final List<String> STAGES=List.of("PROPOSAL","SCHEDULING","CONFIRMED","MEETING"); private final PlanMapper plans; private final ChecklistMapper checklists; private final StagePhotoMapper photos; private final RoomMemberMapper members; public PlanService(PlanMapper p,ChecklistMapper c,StagePhotoMapper s,RoomMemberMapper m){plans=p;checklists=c;photos=s;members=m;}
 @Transactional public PlanResponses.Detail create(long room,long user,PlanRequests.Create r){member(room,user); Plan p=new Plan();p.setRoomId(room);p.setWriterId(user);p.setTitle(r.title());p.setPlanDate(r.planDate());p.setDescription(r.description());plans.insert(p);return detail(p.getId(),user);}
 public PlanResponses.Items<PlanResponses.Summary> list(long room,long user,String status,LocalDate from,LocalDate to){member(room,user);return new PlanResponses.Items<>(plans.findByRoomId(room,status,from,to).stream().map(PlanResponses.Summary::from).toList());}
 public PlanResponses.Detail detail(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);return PlanResponses.Detail.from(p,checklists.findByPlanId(id));}
 @Transactional public PlanResponses.Detail update(long id,long user,PlanRequests.Update r){Plan p=plan(id);member(p.getRoomId(),user);if(plans.updateByIdAndWriterId(id,user,r)!=1)throw new DomainException(ErrorCode.NOT_WRITER);return detail(id,user);}
 @Transactional public void delete(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);if(plans.deleteByIdAndWriterId(id,user)!=1)throw new DomainException(ErrorCode.NOT_WRITER);}
 @Transactional public PlanResponses.Detail complete(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);plans.complete(id,LocalDateTime.now(ZoneOffset.UTC));return detail(id,user);}
 @Transactional public PlanResponses.Detail cancel(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);if(plans.cancelByIdAndWriterId(id,user)!=1)throw new DomainException(ErrorCode.NOT_WRITER);return detail(id,user);}
 @Transactional public PlanResponses.Detail skip(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);plans.skipMemory(id);return detail(id,user);}
 @Transactional public PlanResponses.Checklist addChecklist(long id,long user,PlanRequests.Checklist r){Plan p=plan(id);member(p.getRoomId(),user);PlanChecklist c=new PlanChecklist();c.setPlanId(id);c.setContent(r.content());checklists.insert(c);return PlanResponses.Checklist.from(c);}
 @Transactional public PlanResponses.Checklist updateChecklist(long id,long user,PlanRequests.ChecklistUpdate r){PlanChecklist c=checklists.findById(id).orElseThrow(()->new DomainException(ErrorCode.NOT_FOUND));Plan p=plan(c.getPlanId());member(p.getRoomId(),user);checklists.update(id,r);return PlanResponses.Checklist.from(checklists.findById(id).orElseThrow());}
 @Transactional public void deleteChecklist(long id,long user){PlanChecklist c=checklists.findById(id).orElseThrow(()->new DomainException(ErrorCode.NOT_FOUND));member(plan(c.getPlanId()).getRoomId(),user);checklists.deleteById(id);}
 public PlanResponses.Items<PlanResponses.Stage> stages(long id,long user){Plan p=plan(id);member(p.getRoomId(),user);return new PlanResponses.Items<>(stageItems(id));}
 public PlanResponses.Presign presign(long id,long user,PlanRequests.Presign r){Plan p=plan(id);member(p.getRoomId(),user);assertStageAvailable(id,r.stage());return new PlanResponses.Presign("pending-storage-signature", "pending-storage-image-url",300);}
 @Transactional public PlanResponses.Stage commit(long id,long user,PlanRequests.Stage r){Plan p=plan(id);member(p.getRoomId(),user);assertStageAvailable(id,r.stage());if(photos.existsByPlanIdAndStage(id,r.stage()))throw new DomainException(ErrorCode.STAGE_ALREADY_UPLOADED);PlanStagePhoto photo=new PlanStagePhoto();photo.setPlanId(id);photo.setStage(r.stage());photo.setImageUrl(r.imageUrl());photo.setUploadedBy(user);photos.insert(photo);return stageItems(id).stream().filter(s->s.stage().equals(r.stage())).findFirst().orElseThrow();}
 private List<PlanResponses.Stage> stageItems(long id){Map<String,PlanStagePhoto> map=new HashMap<>();for(PlanStagePhoto p:photos.findByPlanId(id))map.put(p.getStage(),p);List<PlanResponses.Stage> out=new ArrayList<>();boolean previousDone=true;for(String s:STAGES){PlanStagePhoto p=map.get(s);String state=p!=null?"DONE":previousDone?"ACTIVE":"LOCKED";out.add(new PlanResponses.Stage(s,state,p==null?null:p.getImageUrl(),p==null?null:new PlanResponses.Writer(String.valueOf(p.getUploadedBy()),p.getNickname(),p.getProfileImageUrl()),p==null?null:p.getCreatedAt()));previousDone=p!=null;}return out;}
 private void assertStageAvailable(long id,String stage){int index=STAGES.indexOf(stage);if(index<0||index>0&&!photos.existsByPlanIdAndStage(id,STAGES.get(index-1)))throw new DomainException(ErrorCode.STAGE_LOCKED);}
 private Plan plan(long id){return plans.findById(id).orElseThrow(()->new DomainException(ErrorCode.NOT_FOUND));} private void member(long room,long user){if(members.findActiveByRoomIdAndUserId(room,user).isEmpty())throw new DomainException(ErrorCode.ROOM_MEMBER_NOT_FOUND);} }
